name: Artifact Upload and Download Example
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: echo "Data file" > data.txt

      - name: Upload file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: datafile
          path: data.txt

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Download artifact file
        uses: actions/download-artifact@v4
        with:
          name: datafile

      - name: Show file content
        run: cat data.txt
