name: Env Demo
on: [push]
jobs:
  env-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print predefined env
        run: echo "Repo Name is $GITHUB_REPOSITORY"

      - name: Set and print custom env
        run: |
          MYNAME="Yogitha"
          echo "My name is $MYNAME"
