name: File Operations
on: workflow_dispatch
jobs:
  files:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: echo "This is a test file" > demo.txt

      - name: Show file content
        run: cat demo.txt

      - name: List files
        run: ls -l
