name: Docker Matrix
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ub
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, windows-latest]
        images: [hello-world, alpine]
    steps:
      - name: Docker details
        run: docker info
      - name: Run image
        run: docker run ${{ matrix.images }}
