name: Multiple commands in one step
on: workflow_dispatch
jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Multiple commands in one step
        run: |
          echo "This is sample line"
          ls -l
          cat sample.txt
          pwd
          df -h
