name: Parallel jobs demo
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Job1 Step
        run: echo "This is Job1 running"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Job2 Step
        run: echo "This is Job2 running"
