name: Secrets example
on: workflow_dispatch
jobs:
  demo:
    runs-on: ubuntu-22.04
    steps:
      - name: Use secret key
        env:
          KEY: ${{ secrets.API_KEY }}
        run: |
          echo "Secret key received"
          echo "$KEY"
