name: Strings demo
on: workflow_dispatch
jobs:
  strings:
    runs-on: ubuntu-latest
    steps:
      - name: Convert to uppercase
        run: echo "hello from github" | tr 'a-z' 'A-Z'

      - name: Word count
        run: echo "Learning Github actions" | wc -w
