name: test workkflow
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from Job1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from job2"
