name: Job Level Env Example
on: workflow_dispatch
jobs:
  example:
    runs-on: ubuntu-latest
    env:
      COMPANY: ABC Org
      COUNTRY: India

    steps:
      - name: Step one
        run: echo "Company is $COMPANY"

      - name: Step two
        run: echo "Country is $COUNTRY"
